const { EventEmitter } = require("events");

/* 
  The 'error' events that are generated by the captureRejections behavior do not 
  have a catch handler to avoid infinite error loops: the recommendation is to not
  use async functions as 'error' event handlers.
*/
const ee1 = new EventEmitter({ captureRejections: true });
ee1.on("something", async (value) => {
  throw new Error("kaboom");
});

ee1.on("error", console.log);

const ee2 = new EventEmitter({ captureRejections: true });
ee2.on("something", async (value) => {
  throw new Error("kaboom");
});

ee2[Symbol.for("nodejs.rejection")] = console.log;
